### ISSUE TITLE
Never generates 1?

### ISSUE THREAD

**Issue by bkazez** [stesla/base32#17]
From `base32.rb` – shouldn't there be a 1 in this table?
```
  TABLE = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.freeze
```

**Comment by zofrex** [comment]
According to [RFC 3438](https://datatracker.ietf.org/doc/html/rfc3548#section-5), the Base32 alphabet contains a–z and 2–7 — no "0" and no "1".
